version: '2'
services:
  master:
    build: .
    image: rosev3-master
    container_name: master
    networks:
      rosnet:
        ipv4_address: 192.168.0.100
    extra_hosts:
      - "ev3dev:192.168.0.29"
    environment:
      - "ROS_MASTER_URI=http://master:11311"
    command: roscore -v

networks:
  rosnet:
    driver: macvlan
    driver_opts:
      parent: enp0s25  
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1  
